document:
  name: Strategia nazionale per le competenze digitali 
  description: |
     Strategia nazionale per le competenze digitali 
  tags:
    - strategia nazionale 
    - competenze digitali
    - trasformazione digitale 
